#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:backofficeDb
#    #url: jdbc:h2:file:/Users/parkkyutae/Documents/sources/github/fastcampus-demo-01/record-example/sample1/backofficeDb
#    driver-class-name: org.h2.Driver
#    username: root
#    password: '1111'
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    generate-ddl: true
#    properties:
#      format_sql: true
#      hibernate:
#        show-sql: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#  mustache:
#    suffix: .html
#logging:
#  level:
#    org.hibernate.SQL: trace
#    org.hibernate.type: trace
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true